apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sshd.fullname" . }}
  labels:
    {{- include "sshd.labels" . | nindent 4 }}
data:
  sshd_config: |
    PidFile none
    Port {{ .Values.service.port }}
    {{- if .Values.hostKeysSecret }}
    HostKey /etc/ssh/ssh-host-keys/ssh_host_rsa_key
    HostKey /etc/ssh/ssh-host-keys/ssh_host_ecdsa_key
    HostKey /etc/ssh/ssh-host-keys/ssh_host_ed25519_key
    {{- else if .Values.hostKeys }}
    {{- range $file,$keys := .Values.hostKeys.keys }}
    HostKey /etc/sshd/ssh-host-keys/{{ $file }}
    {{- end }}
    {{- else }}
    HostKey /tmp/ssh_host_rsa_key
    HostKey /tmp/ssh_host_ecdsa_key
    HostKey /tmp/ssh_host_ed25519_key
    {{- end }}
    PermitRootLogin no
    PasswordAuthentication no
    ChallengeResponseAuthentication no
    AllowAgentForwarding no
    AllowTcpForwarding no
    X11Forwarding no
    PermitTTY yes
    PrintMotd no
    AcceptEnv LANG LC_*
    # override default of no subsystems
    Subsystem       sftp    /usr/lib/openssh/sftp-server
    StrictModes no
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sshd.fullname" . }}-passwd
  labels:
    {{- include "sshd.labels" . | nindent 4 }}
data:
  passwd: |
    root:x:0:0:root:/root:/bin/bash
    daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
    bin:x:2:2:bin:/bin:/usr/sbin/nologin
    sys:x:3:3:sys:/dev:/usr/sbin/nologin
    sync:x:4:65534:sync:/bin:/bin/sync
    games:x:5:60:games:/usr/games:/usr/sbin/nologin
    man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
    lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
    mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
    news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
    uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
    proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
    www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
    backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
    list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
    irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
    gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
    nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
    _apt:x:100:65534::/nonexistent:/usr/sbin/nologin
    systemd-timesync:x:101:102:systemd Time Synchronization,,,:/run/systemd:/usr/sbin/nologin
    systemd-network:x:102:103:systemd Network Management,,,:/run/systemd:/usr/sbin/nologin
    systemd-resolve:x:103:104:systemd Resolver,,,:/run/systemd:/usr/sbin/nologin
    messagebus:x:104:105::/nonexistent:/usr/sbin/nologin
    Debian-exim:x:105:106::/var/spool/exim4:/usr/sbin/nologin
    sshd:x:106:65534::/run/sshd:/usr/sbin/nologin
    #user:x:1001:1001:SSHD user:/tmp:/usr/sbin/nologin
  {{- range $username,$user := .Values.users }}
    {{ $username }}:x:{{ $user.uid }}:{{ $user.gid | default "100" }}::{{ $user.home }}:{{ $user.shell | default "/bin/sh" }}
  {{- end }}
{{- range $username,$user := .Values.users }}
{{- if $user.authorized_keys }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sshd.fullname" $ }}-user-{{ $username }}
  labels:
    {{- include "sshd.labels" $ | nindent 4 }}
data:
  authorized_keys: |
  {{- range $user.authorized_keys }}
    {{ . }}
  {{- end }}
{{- end }}
{{- end }}
