{{- if .Values.hostKeys -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sshd.fullname" . }}-host-keys
  labels:
    {{- include "sshd.labels" . | nindent 4 }}
type: Opaque
{{ if .Values.hostKeys.base64 }}data:{{ else }}stringData:{{ end }}
{{- range $file,$keys := .Values.hostKeys.keys }}
  {{ $file }}: |
    {{- $keys.key | nindent 4 }}
  {{ $file }}.pub: |
    {{- $keys.pub | nindent 4 }}
{{- end }}
{{- end -}}
