# Default values for mytardis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  clusterDomain: "cluster.local"
  postgresql:
    postgresqlDatabase: "mytardis"
    postgresqlUsername: "mytardis"
    #postgresqlPassword: ""
    #servicePort: 5432
  rabbitmq:
    #host: ""
    #password: &rabbitmqPwd "CHANGEME"
    port: &rabbitmqPort 5672
    user: &rabbitmqUser "mytardis"
    vhost: &rabbitmqVhost "/"
  #storageClassName: ""

tardis:
  enabled: true
  postgresql:
    postgresqlPassword: &postgresqlPwd "mytardis"
  rabbitmq:
    auth:
      password: &rabbitmqPwd "mytardis"
      username: &rabbitmqUser "mytardis"

postgresql:
  enabled: false
  # NB: Sync with .settings.postgresql settings!
  postgresqlPassword: *postgresqlPwd

rabbitmq:
  enabled: false
  auth:
    # NB: Sync with .settings.rabbitmq.password
    password: *rabbitmqPwd
    username: *rabbitmqUser

sshd:
  enabled: false
