# Default values for mytardis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  clusterDomain: "cluster.local"
  postgresql:
    postgresqlDatabase: "mytardis"
    postgresqlUsername: "mytardis"
    #postgresqlPassword: ""
    #servicePort: 5432
  rabbitmq:
    #host: ""
    #password: &rabbitmqPwd "CHANGEME"
    port: &rabbitmqPort 5672
    user: &rabbitmqUser "mytardis"
    vhost: &rabbitmqVhost "/"
  #storageClassName: ""

tardis:
  enabled: true
  postgresql:
    postgresqlPassword: &postgresqlPwd "mytardis"
  rabbitmq:
    auth:
      password: &rabbitmqPwd "mytardis"
      username: &rabbitmqUser "mytardis"

postgresql:
  enabled: false
  # postgresqlPassword required if configured via the Helm chart
  # NB: Sync with .settings.postgresql.postgresqlPassword settings!
  postgresqlPassword: *postgresqlPwd
  # External hosted database settings
  # Required if Postgresql is an external service to this Helm chart
  #addresses:
  #  - ip: 1.1.1.1
  # Used if the external datbase is referenced via a pre-existing DNS name
  #externalName: my.database.example.com
  #port: 5432

rabbitmq:
  enabled: false
  auth:
    # NB: Sync with .settings.rabbitmq.password
    password: *rabbitmqPwd
    username: *rabbitmqUser
  # External hosted rabbitmq settings
  # Required if RabbitMQ is an external service to this Helm chart
  #addresses:
  #  - ip: 1.1.1.1
  # Used if the external RabbitMQ instance is referenced via a pre-existing DNS name
  #externalName: my.rabbitmq.example.com
  #port: 5672

sshd:
  enabled: false
