apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mytardis.fullname" . }}-celery-beat
  labels:
    {{- include "mytardis.labels" . | nindent 4 }}
spec:
  {{- if not .Values.celery.beat.autoscaling.enabled }}
  replicas: {{ .Values.celery.beat.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mytardis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum | quote }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum | quote }}
        {{- with .Values.celery.beat.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "mytardis.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mytardis.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-celery-beat
          args: ['celery','beat','-l',{{ .Values.celery.beat.loglevel | quote }}]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          #ports:
          #  - name: celery
          #    containerPort: 6666
          #    protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /login
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /login
          #    port: http
          resources:
            {{- toYaml .Values.celery.beat.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/app/tardis/settings.py"
              name: settings-py
              readOnly: true
              subPath: settings.py
            - mountPath: "/app/tardis/secrets"
              name: secrets
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: "settings-py"
          configMap:
            name: {{ include "mytardis.fullname" . }}
            items:
              - key: "settings.py"
                path: "settings.py"
        - name: "secrets"
          secret:
            secretName: {{ include "mytardis.fullname" . }}
