{{- if not .Values.postgresql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    {{- include "mytardis.labels" . | nindent 4 }}
spec:
  {{- if .Values.postgresql.externalName }}
  externalName: {{ .Values.postgresql.externalName }}
  type: ExternalName
  {{- else }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: {{ include "mytardis.postgresql.port" . }}
  {{- end }}
{{- if not .Values.postgresql.externalName }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    {{- include "mytardis.labels" . | nindent 4 }}
subsets:
  - addresses:
      - ip: 1.1.1.1
    ports:
      - port: {{ include "mytardis.postgresql.port" . }}
{{- end -}}
{{- end -}}
