apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mytardis-web.fullname" . }}
  labels:
    {{- include "mytardis-web.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- $Values := . -}}
  {{- with .Values.settings }}
  __init__.py: |
    from .settings import *
    from .postgresql import *
    from .broker import *
    {{- if .ldap }}
    from .ldap import *
    {{- end }}
  settings.py: |
    SECRET_KEY = {{ .secret_key | quote }}
  broker.py: |
    BROKER_URL = 'amqp://%(user)s:%(password)s@%(host)s:%(port)s/%(vhost)s' % {
        'host': {{ include "mytardis-web.rabbitmq.host" $ | quote }},
        'port': {{ $.Values.global.rabbitmq.port }},
        'user': {{ $.Values.global.rabbitmq.user | quote }},
        'password': {{ $.Values.global.rabbitmq.password | quote }},
        'vhost': {{ $.Values.global.rabbitmq.vhost | quote }}
    }
  postgresql.py: |
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'HOST': {{ include "mytardis-web.postgresql.host" $Values | quote }},
            'PORT': {{ include "mytardis-web.postgresql.port" $Values }},
            'USER': {{ include "mytardis-web.postgresql.user" $Values | quote }},
            'PASSWORD': {{ include "mytardis-web.postgresql.password" $Values | quote }},
            'NAME': {{ include "mytardis-web.postgresql.name" $Values | quote }},
            'DISABLE_SERVER_SIDE_CURSORS': True,
            'CONN_MAX_AGE': {{ include "mytardis-web.postgresql.conn_max_age" . }}
        }
    }
  {{- if .ldap }}
  {{- with .ldap }}
  ldap.py: |
    LDAP_USE_TLS = {{ if .tls }}True{{ else }}False{{ end }}
    LDAP_URL = {{ .url | quote }}
    LDAP_USER_LOGIN_ATTR = {{ .user_login_attr | quote }}
    LDAP_USER_ATTR_MAP = {
      {{- range $key,$value := .user_attr_map }}
        {{ $key | quote }}: {{ $value | quote }},
      {{- end }}
    }
    LDAP_GROUP_ID_ATTR = {{ .group_id_attr | quote }}
    LDAP_GROUP_ATTR_MAP = {
      {{- range $key,$value := .group_attr_map }}
        {{ $key | quote }}: {{ $value | quote }},
      {{- end }}
    }
    LDAP_ADMIN_USER = {{ .admin_user | quote }}
    LDAP_ADMIN_PASSWORD = {{ .admin_password | quote }}
    LDAP_BASE = {{ .base | quote }}
    LDAP_USER_BASE = {{ .user_base | quote }}
    LDAP_GROUP_BASE = {{ .group_base | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
