apiVersion: v1
kind: Service
metadata:
  name: {{ include "mytardis-web.fullname" . }}-django
  labels:
    {{- include "mytardis-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.django.service.type }}
  ports:
    - port: {{ .Values.django.service.port }}
      targetPort: django
      protocol: TCP
      name: django
  selector:
    {{- include "mytardis-web.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mytardis-web.fullname" . }}-static
  labels:
    {{- include "mytardis-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.static.service.type }}
  ports:
    - port: {{ .Values.static.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mytardis-web.selectorLabels" . | nindent 4 }}
