{{- if .Values.ingress.enabled -}}
{{- $KubeVersion := .Capabilities.KubeVersion.GitVersion -}}
{{- $fullName := include "tardis.fullname" . -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "tardis.fullname" . }}
  labels:
    {{- include "tardis.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
        {{- if .paths }}
          {{- range .paths }}
          - path: {{ .path }}
            {{- if semverCompare ">=1.19-0" $KubeVersion }}
            pathType: {{ default .pathType "Prefix" }}
            backend:
              service:
                name: {{ printf "%s-%s-headless" $fullName .serviceName | quote }}
                port:
                  name: {{ default .servicePort .serviceName }}
            {{- else }}
            backend:
              serviceName: {{ printf "%s-%s-headless" $fullName .serviceName | quote }}
              servicePort: {{ default .servicePort .serviceName }}
            {{- end }}
          {{- end }}
        {{- else }}
          - path: "/"
            {{- if semverCompare ">=1.19-0" $KubeVersion }}
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-%s-headless" $fullName "django" | quote }}
                port:
                  name: django
            {{- else }}
            backend:
              serviceName: {{ printf "%s-%s-headless" $fullName "django" | quote }}
              servicePort: django
            {{- end }}
          - path: "/static/"
            {{- if semverCompare ">=1.19-0" $KubeVersion }}
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-%s-headless" $fullName "static" | quote }}
                port:
                  name: static
            {{- else }}
            backend:
              serviceName: {{ printf "%s-%s-headless" $fullName "static" | quote }}
              servicePort: static
            {{- end }}
        {{- end }}
  {{- end }}
  {{- end }}
