apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tardis.fullname" . }}-files-store
  labels:
    {{- include "tardis.labels" . | nindent 4 }}
spec:
  {{- with .Values.settings.file_store }}
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests:
      storage: {{ .capacity | quote }}
  {{- if (or .storageClass $.Values.global.storageClass) }}
  storageClassName: {{ .storageClass | default $.Values.global.storageClass | quote }}
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tardis.fullname" . }}-receive
  labels:
    {{- include "tardis.labels" . | nindent 4 }}
spec:
  {{- with .Values.settings.default.receiving_dir }}
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests:
      storage: {{ .capacity | quote }}
  {{- if (or .storageClass $.Values.global.storageClass) }}
  storageClassName: {{ .storageClass | default $.Values.global.storageClass | quote }}
  {{- end }}
  {{- end }}
