apiVersion: v1
kind: Service
metadata:
  name: {{ include "tardis.fullname" . }}-django
  labels:
    {{- include "tardis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.django.service.type }}
  ports:
    - port: {{ .Values.django.service.port }}
      targetPort: django
      protocol: TCP
      name: django
  selector:
    {{- include "tardis.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tardis.fullname" . }}-django-headless
  labels:
    {{- include "tardis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.django.service.port }}
      targetPort: django
      protocol: TCP
      name: django
  selector:
    {{- include "tardis.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tardis.fullname" . }}-static
  labels:
    {{- include "tardis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.static.service.type }}
  ports:
    - port: {{ .Values.static.service.port }}
      targetPort: static
      protocol: TCP
      name: static
  selector:
    {{- include "tardis.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tardis.fullname" . }}-static-headless
  labels:
    {{- include "tardis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.static.service.port }}
      targetPort: static
      protocol: TCP
      name: static
  selector:
    {{- include "tardis.selectorLabels" . | nindent 4 }}
